name: ncf
channels:
- nodefaults
- conda-forge
- pytorch
dependencies:
- python=3.7
- cudatoolkit=10.1
- pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
- torchvision=0.5.0=py37_cu101
- numpy
- tqdm
- pyembree
- shapely
- xxhash
- trimesh
- eigenpy
- rtree
- scikit-image==0.16.2
- matplotlib
- scipy
- imageio
- cython
- pip
- pip:
  - pypng
  - pysdf
  - pyrender
  - tensorboard
  - transforms3d
  - opencv-python
  - Pillow==8.2.0
  - git+https://github.com/hassony2/chumpy.git
  - git+https://github.com/mmatl/pyopengl.git
